# basic options
title: Your awesome title
author: Ezzedine Fitouri
email: your-email@domain.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  https://evanwill.github.io/go-go-ghpages/5-reference.html

# Build settings
markdown: kramdown
theme: minima
